# Generated by Django 6.0.5 on 2026-05-24 07:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Бренд')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('rarity', models.CharField(choices=[('common', 'Обычная'), ('rare', 'Редкая'), ('ultra_rare', 'Ультра-редкая'), ('limited', 'Лимитированная'), ('legendary', 'Легендарная')], default='common', max_length=20, verbose_name='Редкость')),
                ('year', models.PositiveIntegerField(verbose_name='Год выпуска')),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Примерная рыночная цена')),
                ('condition', models.CharField(choices=[('mint', 'Mint (идеальное)'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('played', 'Played'), ('poor', 'Poor')], default='mint', max_length=20, verbose_name='Состояние')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='toys/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='toys.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='toys.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Игрушка',
                'verbose_name_plural': 'Игрушки',
                'ordering': ['-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_condition', models.CharField(choices=[('mint', 'Mint (идеальное)'), ('near_mint', 'Near Mint'), ('excellent', 'Excellent'), ('good', 'Good'), ('played', 'Played'), ('poor', 'Poor')], default='mint', max_length=20, verbose_name='Моё состояние')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена покупки')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.toy', verbose_name='Игрушка')),
            ],
            options={
                'verbose_name': 'Элемент коллекции',
                'verbose_name_plural': 'Коллекция пользователя',
                'ordering': ['-added_at'],
                'unique_together': {('user', 'toy')},
            },
        ),
    ]
